const MAIN_COLOR = '#00A536';
const SECONDARY_COLOR = '#0B132A';
const DARK_GREY_COLOR = '#4F5665';
const LIGHT_COLOR_1 = '#FFFFFF';
const LIGHT_COLOR_2 = '#FEFEFE';
const LIGHT_COLOR_3 = '#FBFBFB';
const LIGHT_COLOR_4 = '#F8F8F8';

export {
  MAIN_COLOR,
  SECONDARY_COLOR,
  DARK_GREY_COLOR,
  LIGHT_COLOR_1,
  LIGHT_COLOR_2,
  LIGHT_COLOR_3,
  LIGHT_COLOR_4,
};
